KatmanlıMimariProje/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KatmanlıMimariProje.Controllers
{
    public class CategoryController : Controller
    {
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        ProductManager productManager = new ProductManager(new EfProductDal());

        [HttpGet]
        public IActionResult Index()
        {
            var values = categoryManager.TGetList();
            return View(values);
        }
        public IActionResult DeleteCategory(Category p)
        {
            var products = productManager.GetProductsByCategoryId(p.Id);

            if(products.Any())
            {
                return RedirectToAction("Index");

            }
            var value = categoryManager.TGetByID(p.Id);
            categoryManager.TDelete(value);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult AddCategory(Category p1)
        {
            categoryManager.TInsert(p1);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult AddCategory()
        {

            return View();
        }
    }
}

KatmanlıMimariProje/Controllers/JobController.cs
using BusinessLayer.Concrete;
using BusinessLayer.FluentValidation;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KatmanlıMimariProje.Controllers
{
    public class JobController : Controller
    {

        JobManager jobManager = new JobManager(new EfJobDal());
        public IActionResult Index()
        {
            var values = jobManager.TGetList();
            return View(values);


        }
        [HttpGet]
        public IActionResult AddJob()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddJob(Job veri)
        {
            JobValidator validationRules = new JobValidator();
            ValidationResult results = validationRules.Validate(veri);
            if (results.IsValid)
            {
                jobManager.TInsert(veri);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();

        }

        public IActionResult DeleteJob(Job veri)
        {
            int valueFind = veri.JobID;
            var value = jobManager.TGetByID(valueFind);
            jobManager.TDelete(value);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult UpdateJob(int id)
        {
            var value = jobManager.TGetByID(id);
            TempData["JobID"] = id;
            return View(value);
        }
        [HttpPost]
        public IActionResult UpdateJob(Job veri)
        {
            JobValidator validationRules = new JobValidator();
            ValidationResult results = validationRules.Validate(veri);
            var JobID = TempData["JobID"] as int?;

            if (JobID != null)
            {
                if (veri.JobID == JobID && results.IsValid)
                {

                    jobManager.TUpdate(veri);
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in results.Errors)
                    {
                        ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    }

                }
            }


            return View();
        }
    }
}

KatmanlıMimariProje/Controllers/ProductController.cs
using BusinessLayer.Concrete;
using BusinessLayer.FluentValidation;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KatmanlıMimariProje.Controllers
{
    public class ProductController : Controller
    {
        ProductManager productManager = new ProductManager(new EfProductDal());
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        public IActionResult Index()
        {
            var values = productManager.GetProductsListWithCategory();
            return View(values);


        }
        [HttpGet]
        public IActionResult AddProduct()
        {
            List<SelectListItem> values = (from x in categoryManager.TGetList()
                                           select new SelectListItem
                                           {
                                               Text = x.Name,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.v1 = values;
            return View();
        }
        [HttpPost]
        public IActionResult AddProduct1(Product veri)
        {
            Productvalidator validationRules = new Productvalidator();
            ValidationResult results = validationRules.Validate(veri);
            if (results.IsValid)
            {
                productManager.TInsert(veri);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();

        }

        public IActionResult DeleteProduct(Product veri)
        {
            int valueFind = veri.Id;
            var value = productManager.TGetByID(valueFind);
            productManager.TDelete(value);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult UpdateProduct(int id)
        {
            var value = productManager.TGetByID(id);
            TempData["productID"] = id;
            return View(value);
        }
        [HttpPost]
        public IActionResult UpdateProduct(Product veri)
        {
            Productvalidator validationRules = new Productvalidator();
            ValidationResult results = validationRules.Validate(veri);
            var ProductId = TempData["ProductID"] as int?;

            if (ProductId != null)
            {
                if (veri.Id == ProductId && results.IsValid)
                {

                    productManager.TUpdate(veri);
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in results.Errors)
                    {
                        ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    }

                }
            }


            return View();
        }
    }
}

KatmanlıMimariProje/Controllers/SaleController.cs
using BusinessLayer.Concrete;
using BusinessLayer.FluentValidation;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using KatmanlıMimariProje.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;

using System.Linq;
using System.Threading.Tasks;

namespace KatmanlıMimariProje.Controllers
{
    public class SaleController : Controller
    {
        SaleManager saleManager = new SaleManager(new EfSaleDal());
        ProductManager productManager = new ProductManager(new EfProductDal());
        CustomerManager customerManager = new CustomerManager(new EfCustomerDal());

        public IActionResult Index()
        {
            var values = saleManager.GetSalesListWithProductCustomer();
            return View(values);
        }
        [HttpGet]
        public IActionResult SaleProduct(int id)
        {

            var values = productManager.TGetByID(id);
            var viewModel1 = ConvertToSaleProductCustomViewModel(values); 
            List<SelectListItem> values1 = (from x in customerManager.TGetList()
                                            select new SelectListItem
                                           {
                                               Text = x.Name,
                                                Value = x.ID.ToString()

                                            }).ToList();

            List<SelectListItem> values2 = (from x in productManager.SelectedProductItem(id)
                                            select new SelectListItem
                                            {
                                                Text = x.Name,
                                                Value = x.Id.ToString()

                                            }).ToList();

            
            ViewBag.v3 = values2;

            ViewBag.v2 = values1;

            

            TempData["SatılacakÜrünID"] = values.Id;


            HttpContext.Session.SetString("Price", values.Price.ToString());

            
            





            return View(viewModel1);
        }
        [HttpPost]
        public IActionResult SaleProduct1(Sale p1)
        {
            int? SatısÜrünID = TempData["SatılacakÜrünID"] as int?;
            
            decimal price = decimal.Parse(HttpContext.Session.GetString("Price"));

            SaleValidator validationRules = new SaleValidator();
            ValidationResult results = validationRules.Validate(p1);

             decimal TotalPrice = p1.Quantity * p1.Price;

            p1.TotalPrice = TotalPrice;

            if (p1.ProductID == SatısÜrünID  && p1.Price == price)
            {
                
                    saleManager.TInsert(p1);


                return RedirectToAction("Index");
            }

            return View();
        }

        public SaleProductCustomerViewModel ConvertToSaleProductCustomViewModel(Product product)
        {
            
            SaleProductCustomerViewModel viewModel = new SaleProductCustomerViewModel
            {
                

                Id = product.Id,
                Name = product.Name,
                Price = product.Price,
               
            };

            return viewModel;
        }
    }
}

KatmanlıMimariProje/Views/Shared/_UILayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

@{ await Html.RenderPartialAsync("~/Views/Partials/Partial_Header.cshtml");}




<body>


    @{ await Html.RenderPartialAsync("~/Views/Partials/Partial_Navbar.cshtml");}





    <div id="layoutSidenav">



        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">İşlemler</div>
                        <a class="nav-link" href="@Url.Action("AddProduct","Product")">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-user-plus"></i></div>
                            Ürün Ekle
                        </a>
                        <a class="nav-link" href="@Url.Action("AddCustomer","Customer")">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-user-plus"></i></div>
                            Müşteri Ekle
                        </a>
                        <a class="nav-link" href="@Url.Action("AddJob","Job")">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-user-plus"></i></div>
                            Meslek Ekle
                        </a>
                        <a class="nav-link" href="@Url.Action("AddCategory","Category")">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-user-plus"></i></div>
                            Kategori Ekle
                        </a>

                        <div class="sb-sidenav-menu-heading">Menüler</div>


                        <a class="nav-link" href="@Url.Action("Index","Customer")">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-user-tie"></i></div>
                            Müşteriler
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Sale")">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-list"></i></div>
                            Satışlar
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Category")">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-list"></i></div>
                            Kategoriler
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Product")">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-list"></i></div>
                            Ürünler
                        </a>
                        <a class="nav-link" href="@Url.Action("Index","Job")">
                            <div class="sb-nav-link-icon"><i class="fa-solid fa-list"></i></div>
                            Meslekler
                        </a>

                        

                        <div class="sb-sidenav-menu-heading">Kullanıcı İşlemleri</div>
                        <a class="nav-link" href="@Url.Action("Index","Settings")">
                            <div class="sb-nav-link-icon"><i class="fa fa-lock"></i></div>
                            Kullanıcı Bilgileri İşlemleri
                        </a>
                        <a class="nav-link" href="@Url.Action("LogOut","Login")">
                            <div class="sb-nav-link-icon"><i class="fa fa-close"></i></div>
                            Çıkış Yap
                        </a>

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">
                        <p>Merhaba, @await Component.InvokeAsync("_UILayout")</p>
                    </div>
                    Cengiz Application
                </div>
            </nav>
        </div>





        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4" style="margin-top:40px;">
                    @RenderBody()
                </div>
            </main>

            @{await Html.RenderPartialAsync("~/Views/Partials/Partial_Footer.cshtml");}

        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/startbootstrap-sb-admin-gh-pages/js/scripts.js"></script>


</body>
</html>