KatmanlıMimariProje/Controllers/CustomerController.cs
using BusinessLayer.Concrete;
using BusinessLayer.FluentValidation;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KatmanlıMimariProje.Controllers
{
    public class CustomerController : Controller
    {
        CustomerManager CustomerManager = new CustomerManager(new EfCustomerDal());
        JobManager jobManager = new JobManager(new EfJobDal());

        public IActionResult Index()
        {
            var values = CustomerManager.GetCustomersListWithJob();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddCustomer()
        {
           
            List<SelectListItem> values = (from x in jobManager.TGetList()
                                           select new SelectListItem
                                           {
                                               Text = x.Name,
                                               Value = x.JobID.ToString()
                                           }).ToList();
            ViewBag.v = values;
            return View();
        }
        [HttpPost]
        public IActionResult AddCustomer(Customer p)
        {
            CustomerValidator customerValidator = new CustomerValidator();
            ValidationResult result = customerValidator.Validate(p);
            if (result.IsValid)
            {
                CustomerManager.TInsert(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                

            }
                return View();

        }
        public IActionResult DeleteCustomer(Customer p)
        {
            var value = CustomerManager.TGetByID(p.ID);
            CustomerManager.TDelete(value);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult UpdateCustomer(int id)
        {
            List<SelectListItem> values1 = (from x in jobManager.TGetList()
                                           select new SelectListItem
                                           {
                                               Text = x.Name,
                                               Value = x.JobID.ToString()
                                           }).ToList();
            ViewBag.v1 = values1;
            var values = CustomerManager.TGetByID(id);
            TempData["customerID"] = id;
            return View(values);
        }
        [HttpPost]
        public IActionResult UpdateCustomer(Customer p)
        {

            CustomerValidator customerValidator = new CustomerValidator();
            ValidationResult result = customerValidator.Validate(p);
            var CustomerID = TempData["customerID"] as int?;
            if (CustomerID != null)
            {

                if (p.ID == CustomerID && result.IsValid)
                {

                    CustomerManager.TUpdate(p);
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                       ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                        

                    }

                }
            }
            return View();

        }
    }
}

KatmanlıMimariProje/Controllers/JobController.cs
using BusinessLayer.Concrete;
using BusinessLayer.FluentValidation;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KatmanlıMimariProje.Controllers
{
    public class JobController : Controller
    {

        JobManager jobManager = new JobManager(new EfJobDal());
        public IActionResult Index()
        {
            var values = jobManager.TGetList();
            return View(values);


        }
        [HttpGet]
        public IActionResult AddJob()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddJob(Job veri)
        {
            JobValidator validationRules = new JobValidator();
            ValidationResult results = validationRules.Validate(veri);
            if (results.IsValid)
            {
                jobManager.TInsert(veri);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();

        }

        public IActionResult DeleteJob(Job veri)
        {
            int valueFind = veri.JobID;
            var value = jobManager.TGetByID(valueFind);
            jobManager.TDelete(value);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult UpdateJob(int id)
        {
            var value = jobManager.TGetByID(id);
            TempData["JobID"] = id;
            return View(value);
        }
        [HttpPost]
        public IActionResult UpdateJob(Job veri)
        {
            JobValidator validationRules = new JobValidator();
            ValidationResult results = validationRules.Validate(veri);
            var JobID = TempData["JobID"] as int?;

            if (JobID != null)
            {
                if (veri.JobID == JobID && results.IsValid)
                {

                    jobManager.TUpdate(veri);
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in results.Errors)
                    {
                        ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    }

                }
            }


            return View();
        }
    }
}

KatmanlıMimariProje/Controllers/ProductController.cs
using BusinessLayer.Concrete;
using BusinessLayer.FluentValidation;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KatmanlıMimariProje.Controllers
{
    public class ProductController : Controller
    {
        ProductManager productManager = new ProductManager(new EfProductDal());
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        public IActionResult Index()
        {
            var values = productManager.GetProductsListWithCategory();
            return View(values);


        }
        [HttpGet]
        public IActionResult AddProduct()
        {
            List<SelectListItem> values = (from x in categoryManager.TGetList()
                                           select new SelectListItem
                                           {
                                               Text = x.Name,
                                               Value = x.Id.ToString()
                                           }).ToList();
            ViewBag.v1 = values;
            return View();
        }
        [HttpPost]
        public IActionResult AddProduct1(Product veri)
        {
            Productvalidator validationRules = new Productvalidator();
            ValidationResult results = validationRules.Validate(veri);
            if (results.IsValid)
            {
                productManager.TInsert(veri);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();

        }

        public IActionResult DeleteProduct(Product veri)
        {
            int valueFind = veri.Id;
            var value = productManager.TGetByID(valueFind);
            productManager.TDelete(value);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult UpdateProduct(int id)
        {
            var value = productManager.TGetByID(id);
            TempData["productID"] = id;
            return View(value);
        }
        [HttpPost]
        public IActionResult UpdateProduct(Product veri)
        {
            Productvalidator validationRules = new Productvalidator();
            ValidationResult results = validationRules.Validate(veri);
            var ProductId = TempData["ProductID"] as int?;

            if (ProductId != null)
            {
                if (veri.Id == ProductId && results.IsValid)
                {

                    productManager.TUpdate(veri);
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in results.Errors)
                    {
                        ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    }

                }
            }


            return View();
        }
    }
}

KatmanlıMimariProje/Controllers/SettingsController.cs
using EntityLayer.Concrete;
using KatmanlıMimariProje.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KatmanlıMimariProje.Controllers
{
    public class SettingsController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        public SettingsController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var values =  await _userManager.FindByNameAsync(User.Identity.Name); //sisteme Bağlanan Kullanıcının adından bul
            UserEditViewModel userEditViewModel = new UserEditViewModel();

            userEditViewModel.Name = values.Name;
            userEditViewModel.SurName = values.Surname;
            userEditViewModel.Email = values.Email;
            

            return View(userEditViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Index(UserEditViewModel p)
        {
            var values = await _userManager.FindByNameAsync(User.Identity.Name); //sisteme Bağlanan Kullanıcının adından bul

            values.Name = p.Name;
            values.Surname = p.SurName;
            values.Email = p.Email;
            values.PasswordHash = _userManager.PasswordHasher.HashPassword(values,p.Password);
            var result = await _userManager.UpdateAsync(values);
            if(result.Succeeded)
            {
                return RedirectToAction("Index", "Product");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
                return View();
            }
            
            


            
        }

    }
}

KatmanlıMimariProje/Views/Partials/Partial_Footer.cshtml
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Tüm Hakları Saklıdır @DateTime.Now.Year</div>
            <div>
                <a href="#">Gizlilik İlkeleri</a>
                &middot;
                <a href="#">Şartlar &amp; Koşullar</a>
            </div>
        </div>
    </div>
</footer>

KatmanlıMimariProje/Views/Partials/Partial_Header.cshtml
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Katmanlı Mimari Proje</title>
    <link href="~/startbootstrap-sb-admin-gh-pages/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>

KatmanlıMimariProje/Views/Partials/Partial_Navbar.cshtml
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="index.html">Katmanlı Mimari Proje<br>Asp.Net Core 5.0</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="@Url.Action("Index","Settings")">Ayarlar</a></li>
                <li><a class="dropdown-item" href="@Url.Action("Index","Help")">Yardım</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="@Url.Action("LogOut","Login")">Çıkış Yap</a></li>
            </ul>
        </li>
    </ul>
</nav>

KatmanlıMimariProje/Views/Partials/Partial_SideBar.cshtml
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">İşlemler</div>
                <a class="nav-link" href="@Url.Action("AddProduct","Product")">
                    <div class="sb-nav-link-icon"><i class="fa-solid fa-user-plus"></i></div>
                    Ürün Ekle
                </a>
                <a class="nav-link" href="@Url.Action("AddCustomer","Customer")">
                    <div class="sb-nav-link-icon"><i class="fa-solid fa-user-plus"></i></div>
                    Müşteri Ekle
                </a>
                <a class="nav-link" href="@Url.Action("AddJob","Job")">
                    <div class="sb-nav-link-icon"><i class="fa-solid fa-user-plus"></i></div>
                    Meslek Ekle
                </a>


                <div class="sb-sidenav-menu-heading">Menüler</div>

                <a class="nav-link" href="@Url.Action("Index","Customer")">
                    <div class="sb-nav-link-icon"><i class="fa-solid fa-user-tie"></i></div>
                    Müşteriler
                </a>
                <a class="nav-link" href="tables.html">
                    <div class="sb-nav-link-icon"><i class="fa-solid fa-list"></i></div>
                    Kategoriler
                </a>
                <a class="nav-link" href="@Url.Action("Index","Product")">
                    <div class="sb-nav-link-icon"><i class="fa-solid fa-list"></i></div>
                    Ürünler
                </a>
                <a class="nav-link" href="@Url.Action("Index","Job")">
                    <div class="sb-nav-link-icon"><i class="fa-solid fa-list"></i></div>
                    Meslekler
                </a>

                <a class="nav-link" href="#">
                    <div class="sb-nav-link-icon"><i class="fa-solid fa-circle-info"></i></div>
                    Yardım
                </a>

                <div class="sb-sidenav-menu-heading">Kullanıcı İşlemleri</div>
                <a class="nav-link" href="@Url.Action("Index","Settings")">
                    <div class="sb-nav-link-icon"><i class="fa fa-lock"></i></div>
                    Kullanıcı Bilgileri İşlemleri
                </a>
                <a class="nav-link" href="@Url.Action("LogOut","Login")">
                    <div class="sb-nav-link-icon"><i class="fa fa-close"></i></div>
                    Çıkış Yap
                </a>

            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Merhaba @ViewData["tempdata"]</div>
            Start Bootstrap
        </div>
    </nav>
</div>